---
- name: Build and push Docker image
  hosts: localhost
  vars:
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    dockerhub_username: "{{ lookup('env', 'DOCKER_HUB_LOGIN_USR') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKER_HUB_LOGIN_PSW') }}"
  tasks:
    - name: Build Docker image
      docker_image:
        name: abc_technologies
        tag: "{{ build_number }}"
        path: /home/jenkins/workspace/cicd_ansible_dockerimage  # Assuming Jenkins workspace is correct
        source: build

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        registry_url: "https://index.docker.io/v1/"

    - name: Push Docker image to Docker Hub
      docker_image:
        name: abc_technologies
        tag: "{{ build_number }}"
        source: push
 
